/**
 * `createGitHubOAuthHandler` — the server-side callback leg of the GitHub
 * identity provider (`useAuthProvider({ provider: 'github' })`, ADR 0009).
 *
 * GitHub redirects the sign-in popup here with `?code=&state=`. This handler:
 *   1. validates the query strictly (formats are pinned — anything else is a
 *      400, never reflected);
 *   2. exchanges the code at GitHub's token endpoint — the client secret
 *      stays on this server, and the resulting access token is used for ONE
 *      `/user` lookup and then discarded;
 *   3. responds with a tiny HTML page that `postMessage`s
 *      `{ source: 'scorezilla:github-oauth', state, id }` to `window.opener`,
 *      pinned to `allowedOrigin`, and closes the popup.
 *
 * The browser side (`scorezilla/identity`) accepts the message only when the
 * origin matches its `exchangeUrl` and the `state` echoes the one it
 * generated — this page is the only party that can complete a sign-in.
 *
 * Returns a standard `(Request) => Promise<Response>`: deploy it on any web
 * runtime (a Next.js route handler, Hono, Deno, Bun, a Cloudflare Worker).
 * Configure the deployed URL as the OAuth app's callback URL on GitHub.
 *
 * @since 0.3.0
 */
import type { FetchImpl } from './transport';

const GITHUB_TOKEN_URL = 'https://github.com/login/oauth/access_token';
const GITHUB_USER_URL = 'https://api.github.com/user';

/** Must match `GITHUB_MESSAGE_SOURCE` in `scorezilla/identity` — the marker
 *  the browser half filters callback messages on. */
const MESSAGE_SOURCE = 'scorezilla:github-oauth';

/** GitHub identifies the calling app via User-Agent and rejects without one. */
const USER_AGENT = 'scorezilla-sdk-github-oauth';

// Strict input formats. `state` is generated by the SDK client (base64url
// alphabet); `code` is GitHub-issued. Anything outside these shapes is
// rejected up front and NEVER echoed into the HTML response.
const STATE_RE = /^[A-Za-z0-9_-]{8,128}$/;
const CODE_RE = /^[A-Za-z0-9_-]{1,128}$/;

export interface CreateGitHubOAuthHandlerConfig {
  /** Your GitHub OAuth app client ID. */
  readonly clientId: string;
  /** Your GitHub OAuth app client secret. Server-only — never ships to a browser. */
  readonly clientSecret: string;
  /**
   * The exact origin of the GAME page that opens the sign-in popup, e.g.
   * `https://mygame.example`. Used as the `postMessage` target origin so the
   * sign-in result can only be delivered to your page — never `*`.
   */
  readonly allowedOrigin: string;
  /** Inject a `fetch` (testing / custom transport). */
  readonly fetch?: FetchImpl;
}

/** The web-standard request handler returned by {@link createGitHubOAuthHandler}. */
export type GitHubOAuthHandler = (req: Request) => Promise<Response>;

/**
 * Build the GitHub OAuth callback endpoint. See module docs for the flow;
 * see `GitHubAuthProviderOptions` in `scorezilla/identity` for the matching
 * client half.
 *
 * **Construction patterns.** In Node/Next, secrets are in `process.env`, so
 * build the handler once at module scope. In Cloudflare Workers, secrets
 * live on the per-request `env` binding, so build it inside `fetch`.
 */
export function createGitHubOAuthHandler(
  config: CreateGitHubOAuthHandlerConfig,
): GitHubOAuthHandler {
  if (typeof config.clientId !== 'string' || config.clientId.length === 0) {
    throw new TypeError('createGitHubOAuthHandler: clientId is required.');
  }
  if (typeof config.clientSecret !== 'string' || config.clientSecret.length === 0) {
    throw new TypeError('createGitHubOAuthHandler: clientSecret is required.');
  }
  let allowedOrigin: string;
  try {
    const parsed = new URL(config.allowedOrigin);
    // `origin` normalizes (drops paths, lowercases the host) — and throws
    // above on anything that isn't an absolute URL.
    allowedOrigin = parsed.origin;
    if (allowedOrigin === 'null') throw new Error('opaque origin');
  } catch {
    throw new TypeError(
      'createGitHubOAuthHandler: allowedOrigin must be an absolute origin, ' +
        "e.g. 'https://mygame.example' (got " +
        JSON.stringify(config.allowedOrigin) +
        ').',
    );
  }
  const fetchImpl: FetchImpl = config.fetch ?? fetch;

  return async (req: Request): Promise<Response> => {
    if (req.method !== 'GET') {
      return new Response('method not allowed', { status: 405, headers: { allow: 'GET' } });
    }
    const url = new URL(req.url);
    const state = url.searchParams.get('state') ?? '';
    const code = url.searchParams.get('code');
    const ghError = url.searchParams.get('error');

    // `state` gates EVERY response that echoes anything — validate first.
    if (!STATE_RE.test(state)) {
      return new Response('invalid or missing state parameter', { status: 400 });
    }

    // GitHub-side denial (player cancelled on the consent screen): relay it
    // so the client resolves null. No exchange to attempt.
    if (ghError !== null) {
      return callbackPage(
        { state, error: ghError === 'access_denied' ? 'access_denied' : 'exchange_failed' },
        allowedOrigin,
      );
    }

    if (code === null || !CODE_RE.test(code)) {
      return new Response('invalid or missing code parameter', { status: 400 });
    }

    // Leg 1: code → access token. The secret stays here; the token never
    // leaves this function.
    let accessToken: string;
    try {
      const tokenRes = await fetchImpl(GITHUB_TOKEN_URL, {
        method: 'POST',
        headers: {
          accept: 'application/json',
          'content-type': 'application/x-www-form-urlencoded',
          'user-agent': USER_AGENT,
        },
        body: new URLSearchParams({
          client_id: config.clientId,
          client_secret: config.clientSecret,
          code,
        }).toString(),
      });
      const tokenBody = (await tokenRes.json()) as { access_token?: unknown; error?: unknown };
      if (!tokenRes.ok || typeof tokenBody.access_token !== 'string') {
        return callbackPage({ state, error: 'exchange_failed' }, allowedOrigin);
      }
      accessToken = tokenBody.access_token;
    } catch {
      return callbackPage({ state, error: 'exchange_failed' }, allowedOrigin);
    }

    // Leg 2: token → numeric user id. Only `id` is read; the token is
    // dropped when this function returns.
    try {
      const userRes = await fetchImpl(GITHUB_USER_URL, {
        method: 'GET',
        headers: {
          authorization: `Bearer ${accessToken}`,
          accept: 'application/vnd.github+json',
          'user-agent': USER_AGENT,
        },
      });
      if (!userRes.ok) {
        return callbackPage({ state, error: 'exchange_failed' }, allowedOrigin);
      }
      const user = (await userRes.json()) as { id?: unknown };
      if (typeof user.id !== 'number' || !Number.isSafeInteger(user.id)) {
        return callbackPage({ state, error: 'exchange_failed' }, allowedOrigin);
      }
      return callbackPage({ state, id: String(user.id) }, allowedOrigin);
    } catch {
      return callbackPage({ state, error: 'exchange_failed' }, allowedOrigin);
    }
  };
}

/**
 * The popup's terminal page: deliver the payload to the opener (pinned to
 * `allowedOrigin`) and close. Every interpolated value is JSON.stringify-ed
 * AND pre-validated upstream (`state` against STATE_RE, `id` digits-only,
 * `error` from a fixed vocabulary), so no caller-controlled byte can break
 * out of the script context.
 */
function callbackPage(
  payload: { state: string; id?: string; error?: string },
  allowedOrigin: string,
): Response {
  const message = JSON.stringify({ source: MESSAGE_SOURCE, ...payload });
  const target = JSON.stringify(allowedOrigin);
  const html = `<!doctype html>
<html>
<head><meta charset="utf-8"><title>Signing in…</title></head>
<body>
<script>
(function () {
  if (window.opener) {
    window.opener.postMessage(${message}, ${target});
    window.close();
  } else {
    document.body.textContent =
      'Sign-in handled — you can close this window. (If this keeps appearing, ' +
      'the game page may be setting Cross-Origin-Opener-Policy: same-origin, ' +
      'which severs the popup link; use same-origin-allow-popups.)';
  }
})();
</script>
</body>
</html>`;
  return new Response(html, {
    status: 200,
    headers: {
      'content-type': 'text/html; charset=utf-8',
      // One-shot page embedding a one-shot state — never cache it.
      'cache-control': 'no-store',
      // The URL carried the OAuth `code`; nothing on this page may leak it.
      'referrer-policy': 'no-referrer',
      // Defense in depth for the inline script: nothing else may load or
      // run on this page even if a future regression reflected input here.
      'content-security-policy': "default-src 'none'; script-src 'unsafe-inline'",
      'x-content-type-options': 'nosniff',
    },
  });
}
